name: flink
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  provider: ^6.1.2
  eva_icons_flutter: ^3.1.0
  font_awesome_flutter: ^10.7.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.3
  custom_navigation_bar: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
